### ISSUE TITLE
Cannot connect with latest MC edu

### ISSUE THREAD

**Issue by himemleung** [Nathan-Nesbitt/Minecraft_AI#69]
an't connect with minecraft education v.1.19.52. When I try /connect localhost:5678, the following error appear:

Error in connection handler
Traceback (most recent call last):
File "site-packages\websockets\protocol.py", line 827, in transfer_data
File "site-packages\websockets\protocol.py", line 895, in read_message
File "site-packages\websockets\protocol.py", line 977, in read_data_frame
File "site-packages\websockets\framing.py", line 308, in parse_close
File "site-packages\websockets\framing.py", line 338, in check_close
websockets.exceptions.ProtocolError: invalid status code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "site-packages\websockets\server.py", line 191, in handler
File "src\back_end\broker.py", line 44, in response
File "site-packages\websockets\protocol.py", line 509, in recv
File "site-packages\websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by p0t4t0sandwich** [comment]
Found the solution while working on my own lib.
You now need to disable `Settings` -> `General` -> `Require Encrypted Websockets`
Then it should connect fine

**Comment by himemleung** [comment]
Hi Dylan,

Great thanks for your hints! Seems I can connect now but still not able to establish the command to MC edu. Are you trying v1.19.52?
![conn error](https://github.com/Nathan-Nesbitt/Minecraft_AI/assets/132203325/a39aa9c8-23e1-4567-80c6-0661f3673cae)

**Comment by p0t4t0sandwich** [comment]
I haven't tested this AI lib specifically, but I wonder if some of the internal events have changed in the recent updates.
I'll take a look around those methods and see if I can think of anything
